---
name: "Config"

on:
  workflow_call:

jobs:
  diagnostics:
    name: "Diagnostics"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.4.0
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:443
            azure.archive.ubuntu.com:80
            13.107.43.16:80
            esm.ubuntu.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            www.githubstatus.com:443

      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@v3.2.0
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v2.0.0
